// <auto-generated />
using System;
using Gyoujimaru.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Gyoujimaru.Migrations
{
    [DbContext(typeof(GyoujimaruContext))]
    [Migration("20210722164031_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Gyoujimaru.Services.Olympics._2021.BlockedUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("UserId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("Gyoujimaru.Services.Olympics._2021.CharacterSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<long>("ClaimantId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EliminatedById")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("ClaimantId")
                        .IsUnique();

                    b.HasIndex("EliminatedById");

                    b.ToTable("CharacterSubmissions");
                });

            modelBuilder.Entity("Gyoujimaru.Services.Olympics._2021.CharacterSubmission", b =>
                {
                    b.HasOne("Gyoujimaru.Services.Olympics._2021.CharacterSubmission", "EliminatedBy")
                        .WithMany()
                        .HasForeignKey("EliminatedById");

                    b.Navigation("EliminatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
